% This script takes any Path Matrix: A as input.
% A should be in the structure of [x,y,z]
% You can generate A from any strange path by extracting the x,y,z data
% from your path.

% Load your path to Matrix A, and store it in PathPts Matrix.
% A matrix by default is generated by running GenerateA.m script.
PathPts = A;

% Generate signal
TakeOffTime = 1;
XYflyTime = 2;
tss = 0.1;
Tfinal = XYflyTime + tss*(length(PathPts)-1);
t = 0:tss:Tfinal;

sigZ = [t;0*t];
for i = 1:length(sigZ)
    takeoffindex = (TakeOffTime/tss)+1;
    startindex = (XYflyTime/tss)+1;
    if i < takeoffindex
        sigZ(2,i) = 0
    elseif i < startindex
        sigZ(2,i) = PathPts(1,3)
    else
        sigZ(2,i) = PathPts(i-startindex+1,3)
    end
end
          
sigX = [t;0*t];
sigY = [t;0*t];
for i = 1:length(sigX)
    startindex = (XYflyTime/tss)+1;
    if i < startindex
        sigX(2,i) = 0;
        sigY(2,i) = 0;
    else
        sigX(2,i) = PathPts(i-startindex+1,1)
        sigY(2,i) = PathPts(i-startindex+1,2)
    end
end

Zcmd = timeseries(sigZ(2:end,:),sigZ(1,:))
Ycmd = timeseries(sigY(2:end,:),sigY(1,:))
Xcmd = timeseries(sigX(2:end,:),sigX(1,:))
        
        